### ISSUE TITLE
New expo projects not building when using the latest nitro modules version

### ISSUE THREAD

**Issue by Nekidev** [jpudysz/react-native-unistyles#469]
### Description

The title. I've created a new expo project from scratch (running `bunx create expo-app@latest .`) and then installed unistyles on that new project but the latest nitro modules version causes the builds to fail. I'm posting it here because the documentation indicates to install the latest nitro modules version since it's not a dependency (not sure why?) (it says to run `bun add react-native-nitro-modules` which does install the latest version), but the latest version just doesn't compile.

### Steps to Reproduce

1. Create a new expo project from scratch using `bunx create expo-app@latest .`
2. Install unistyles (the crashing nitro modules is version `v0.20.1`) and set it up (change the entry file to a new `index.ts` and import `expo-router/entry` from there)
3. Run `bunx expo run:android`
4. Watch it crash

### Unistyles Version

3.0.0-beta.1, but it makes no difference with any beta version

### React Native Version

0.76.5

### Platforms

Android

### Expo

Yes

**Comment by Nekidev** [comment]
This fixed when downgrading to `v0.18.2`, but still it's an issue that the library doesn't depend on a fixed version.

**Comment by riccardoratta** [comment]
Seems to fail with `v0.18.2` also. This is the output of my `npm list`:

```
├── @babel/core@7.26.0
├── @expo/vector-icons@14.0.4
├── @react-navigation/bottom-tabs@7.2.0
├── @react-navigation/native@7.0.14
├── @types/jest@29.5.14
├── @types/react-test-renderer@18.3.1
├── @types/react@18.3.18
├── expo-blur@14.0.1
├── expo-constants@17.0.3
├── expo-dev-client@5.0.8
├── expo-font@13.0.2
├── expo-haptics@14.0.0
├── expo-linking@7.0.3
├── expo-router@4.0.15
├── expo-splash-screen@0.29.18
├── expo-status-bar@2.0.0
├── expo-symbols@0.2.0
├── expo-system-ui@4.0.6
├── expo-web-browser@14.0.1
├── expo@52.0.23
├── jest-expo@52.0.2
├── jest@29.7.0
├── react-dom@18.3.1
├── react-native-edge-to-edge@1.2.0
├── react-native-gesture-handler@2.20.2
├── react-native-nitro-modules@0.18.2
├── react-native-reanimated@3.16.6
├── react-native-safe-area-context@4.12.0
├── react-native-screens@4.4.0
├── react-native-unistyles@3.0.0-beta.4
├── react-native-web@0.19.13
├── react-native-webview@13.12.5
├── react-native@0.76.5
├── react-test-renderer@18.3.1
├── react@18.3.1
└── typescript@5.7.2
```

The error is during `npx expo run:ios`:

```
The following build commands failed:
        EmitSwiftModule normal arm64 (in target 'NitroModules' from project 'Pods')
        SwiftEmitModule normal arm64 Emitting\ module\ for\ NitroModules (in target 'NitroModules' from project 'Pods')
```

Before I've cleaned the project with:

- `rm -rf node_modules package-lock.json .expo ios android`
- `npm i`
- `npx expo prebuild --clean`

**Comment by chanphiromsok** [comment]
makes sure enabled new arch and try prebuild I
for me I don't have any issue using expo

**Comment by riccardoratta** [comment]
Thanks for the response @chanphiromsok!

New architecture is enabled by default, the steps to reproduce the error from scratch are the following:

```
npx create-expo-app@latest
cd my-app
npm i react-native-unistyles@beta
npm i react-native-nitro-modules@0.18.2 react-native-edge-to-edge
echo """
module.exports = function (api) {
  api.cache(true)

  return {
    // other config
    plugins: [
        // other plugins
        ['react-native-unistyles/plugin']
    ]
  }
}
""" > babel.config.js
npx expo prebuild --clean
npx expo run:ios
```

By default `newArchEnabled` is set to true in the `app.json`.

I'm building on macOS 15.2 with ARM processor.

**Comment by ilmatic** [comment]
Wow I literally just ran into this exact issue with a new project. Exact same repro steps. Building on macOS 15.0 with ARM processor. Xcode tools @ 16.2

**Comment by ilmatic** [comment]
@riccardoratta I was able to fix with the following steps:

1. Before running `expo prebuild --clean`, update the deployment target of the project (I used 16.6) using expo-build-properties: https://docs.expo.dev/versions/latest/sdk/build-properties/
2. This will update the deployment targets of the project, but somehow doesn't end up making its way all the way thru to the pods, `cd ios` and `rm -rf Pods`, then update this line in your Podfile `platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'` to 16.6. 
3. Add this snippet inside of the `post_install do |installer|` hook:

```
  post_install do |installer|
  # This ensures all the pods adhere to the same deployment target.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.6'
      end
    end
```

---
The issue seems to be that CxxStdlib, which NitroModules depends on, has a minimum deployment target of 16.0. Well, actually it doesn't, but a bug with Xcode 16.2 makes Xcode think it does. Looks like the Swift toolchain has been fixed, but I have the latest Xcode and it still has the bug in Simulator, so not sure when that's all meant to make its way down to production. [GH issue](https://github.com/swiftlang/swift/issues/77909)

FYI -- Step 3 above might not be necessary. I happened to do both 2 and 3 at the same time and now its working and I don't feel like going back to a clean project rn lol. So you might try just Step 2 first and see if that works.

**Comment by chanphiromsok** [comment]
> Thanks for the response @chanphiromsok!
> 
> New architecture is enabled by default, the steps to reproduce the error from scratch are the following:
> 
> ```
> npx create-expo-app@latest
> cd my-app
> npm i react-native-unistyles@beta
> npm i react-native-nitro-modules@0.18.2 react-native-edge-to-edge
> echo """
> module.exports = function (api) {
>   api.cache(true)
> 
>   return {
>     // other config
>     plugins: [
>         // other plugins
>         ['react-native-unistyles/plugin']
>     ]
>   }
> }
> """ > babel.config.js
> npx expo prebuild --clean
> npx expo run:ios
> ```
> 
> By default `newArchEnabled` is set to true in the `app.json`.
> 
> I'm building on macOS 15.2 (Xcode 16.2) with ARM processor.

could you provide the repo ? because I am using the same version don't have any issue
├── react-native-nitro-modules@0.18.2
├── react-native-reanimated@3.16.3
├── react-native-root-siblings@5.0.1
├── react-native-safe-area-context@4.12.0
├── react-native-screens@4.4.0
├── react-native-svg@15.8.0
├── react-native-unistyles@3.0.0-beta.4
├── react-native-web@0.19.13
├── react-native@0.76.5

**Comment by riccardoratta** [comment]
@ilmatic I can confirm that `expo-build-properties` with `deploymentTarget ` set to `16.6` is not enough to compile the project alone.

**Comment by ggraciano** [comment]
Yeah I ran into the same issue that @ilmatic mentioned, but decided to downgrade to Xcode 16.1 instead of fiddling with the config files seeing as the issue should be resolved in the next Xcode release. You can try some of the suggestions mentioned here: https://github.com/mrousavy/nitro/issues/422#issuecomment-2567886671

**Comment by jpudysz** [comment]
Will be fixed with #477 and `beta.5`

**Comment by melv-n** [comment]
> Will be fixed with [#477](https://github.com/jpudysz/react-native-unistyles/pull/477) and `beta.5`

Still seeing this error on XCode 16.2 with unistyles beta.5 and nitro 0.21.0, anything else that needs to happen to build successfully in this environment?

```
<unknown>:0: error: compiling for iOS 15.1, but module 'CxxStdlib' has a minimum deployment target of iOS 16.0: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/CxxStdlib.swiftmodule/arm64-apple-ios-simulator.swiftmodule
```

**Comment by melv-n** [comment]
@jpudysz Thank you! I incorrectly assumed your message meant it was fixed without any needed workarounds.
